Fixed vault and minio
Added proper hostname to vault otherwise ssl verification fails.
Adjusted minio to use u/p that does not contain reserver words.

diff --git a/pxb/v2/docker/run-test b/pxb/v2/docker/run-test
--- a/pxb/v2/docker/run-test
+++ b/pxb/v2/docker/run-test
@@ -2,7 +2,11 @@
 
 set -o errexit
 set -o xtrace
+trap cleanup EXIT
 
+function cleanup (){
+docker rm --force vault s3 kmip
+}
 ROOT_DIR=$(cd $(dirname $0)/../sources; pwd -P)
 SCRIPTS_DIR=$(cd $(dirname $0)/../local; pwd -P)
 SOURCE_IMAGE=${1:-centos:7}
@@ -26,9 +30,9 @@ if [[ ${WITH_XBCLOUD_TESTS} == "true" ]]; then
     if [[ $(docker network list | grep pxb_network) != *pxb_network* ]]; then
         docker network create pxb_network
     fi
-    docker run -d --security-opt seccomp=unconfined --cap-add=NET_ADMIN --rm -p 9000:9000 --rm -p 9001:9001 ${DOCKER_NETWORK_FLAG} --name s3 altmannmarcelo/minio:latest
+    docker run -d --security-opt seccomp=unconfined --cap-add=NET_ADMIN --env PASSWORD=someStrongPWD --env USER=myuser -p 9000:9000 --rm -p 9001:9001 ${DOCKER_NETWORK_FLAG} --name s3 altmannmarcelo/minio:latest
     export S3_SERVER_IP=$(docker inspect s3 | egrep "\"IPAddress\": \"([0-9]{1,3}\.){3}[0-9]{1,3}" | awk -F'"' '{print $4}')
-    export XBCLOUD_CREDENTIALS="--storage=s3 --s3-endpoint='http://${S3_SERVER_IP}:9000' --s3-access-key=admin --s3-secret-key=password --s3-bucket=newbucket"
+    export XBCLOUD_CREDENTIALS="--storage=s3 --s3-endpoint='http://${S3_SERVER_IP}:9000' --s3-access-key=myuser --s3-secret-key=someStrongPWD --s3-bucket=newbucket"
 fi
 
 if [[ ${WITH_VAULT_TESTS} == "true" ]]; then
@@ -37,10 +41,20 @@ if [[ ${WITH_VAULT_TESTS} == "true" ]]; then
     fi
     docker run -d --security-opt seccomp=unconfined --cap-add=NET_ADMIN --rm -p 8200:8200 ${DOCKER_NETWORK_FLAG} --name vault altmannmarcelo/vault:latest
     docker cp vault:/opt/vault/tls/tls.crt ${ROOT_DIR}/vault.crt
-    sleep 10
-
     export VAULT_SERVER_IP=$(docker inspect vault | egrep "\"IPAddress\": \"([0-9]{1,3}\.){3}[0-9]{1,3}" | awk -F'"' '{print $4}')
     export TOKEN=$(docker logs vault | grep 'export VAULT_TOKEN' | awk -F'=' '{print $2}')
+    ATTEMPT=1
+    while [ "${TOKEN}" == "" ];
+    do
+        sleep 2
+        export TOKEN=$(docker logs vault | grep 'export VAULT_TOKEN' | awk -F'=' '{print $2}')
+        if [[ ${ATTEMPT} -eq 10 ]]; then
+            echo "Vault token not found"
+            exit 1
+        fi
+        ATTEMPT=$((ATTEMPT+1))
+    done
+
 fi
 
 if [[ ${WITH_KMIP_TESTS} == "true" ]]; then
@@ -75,14 +89,16 @@ docker run --rm \
     export WITH_AZURITE='${WITH_AZURITE}'
     export LANG=en_AU.UTF-8
     export XBCLOUD_CREDENTIALS='${XBCLOUD_CREDENTIALS}'
-    export VAULT_URL=https://${VAULT_SERVER_IP}:8200
+    export VAULT_IP='${VAULT_SERVER_IP}'
+    export VAULT_URL=https://local.vault.com:8200
     export VAULT_CACERT=/tmp/pxb/vault.crt
     export VAULT_CA=/tmp/pxb/vault.crt
     export VAULT_TOKEN='${TOKEN}'
     export KMIP_CLIENT_CA=/tmp/pxb/client_certificate_jane_doe.pem
     export KMIP_CLIENT_KEY=/tmp/pxb/client_key_jane_doe.pem
     export KMIP_SERVER_CA=/tmp/pxb/root_certificate.pem
-    export KMIP_SERVER_ADDR='${KMIP_SERVER_IP}'
+    export KMIP_SERVER_IP='${KMIP_SERVER_IP}'
+    export KMIP_SERVER_ADDR='local.kmip.com'
     export KMIP_SERVER_PORT=5696
 
     mkdir /tmp/results
